version: '3.1'
services:
  mongo:
    image: mongo
    container_name: dbMongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongoData:/data/db
    environment:
      - MONGODB_DATABASE=nest-poke